=== Aragaki1987/Assembla/calculator/src/com/san/xmlprocessor/kompisSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema
        xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:ivan="http://www.ivan.com/schemas"
        targetNamespace="http://www.ivan.com/schemas"
        attributeFormDefault="unqualified">
    <element name="kompisRelation" type="ivan:KompisRelation"/>
    <element name="person" type="ivan:Person"/>
    <attribute name="eyeColour" type="string" default="blue"/>
    <complexType name="KompisRelation">
        <sequence>
            <element name="person" type="ivan:Person"/>
            <element name="friend" type="ivan:Person" minOccurs="0"
                     maxOccurs="unbounded" nillable="false"/>
        </sequence>
        <attribute name="degree" type="string" use="optional"
                   default="acquaintance"/>
    </complexType>
    <complexType name="Person">
        <sequence>
            <element name="firstName" type="string" nillable="false"/>
            <element name="lastName" type="string" nillable="false"/>
            <element name="age" type="int"/>
            <element name="favColour" type="string" minOccurs="0"
                     maxOccurs="unbounded"/>
        </sequence>
        <attribute ref="ivan:eyeColour"/>
        <attribute name="hasDog" type="boolean"/>
    </complexType>
</schema>

=== Aragaki1987/Assembla/calculator/src/com/san/xmlprocessor/kompisar.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- A comment in the file kompisar.xml -->
<ivan:kompisRelation
        xmlns:ivan="http://www.ivan.com/schemas"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.ivan.com/schemas kompisSchema.xsd"
        degree="closeFriends">
    <person>
        <firstName>Ivan</firstName>
        <lastName>Krizsan</lastName>
        <age>19</age>
    </person>
    <friend ivan:eyeColour="green">
        <firstName>Steven</firstName>
        <lastName>Segal</lastName>
        <age>49</age>
    </friend>
    <friend>
        <firstName>Carl-Gustav</firstName>
        <lastName>Svensson</lastName>
        <age>56</age>
    </friend>
    <!-- There is a deliberate error here. -->
    <friend hasDog="true">
    </friend>
</ivan:kompisRelation>
